export default {
    login :'api/login',
    register:'/api/common/register',
    //查重
    getAccountByEmail:'api/common/getAccountByEmail',
    //sencode
    SendEmail:'api/common/forgetValicode',
    //验证密码
    forgetPass:'api/common/forgetPass',
    //退出登录
    logOut: 'api/logout',
    HomeCate:'api/goodsCate/allGoodsCates',
    shortUrl: 'https://sanyi-x-site.oss-cn-hongkong.aliyuncs.com/temp_api/',
    HomeData:'api/goods/getIndexGoods',
    SearchGoods:'api/search/query',
    getUserInfo:'api/customer/queryCustomerInfo',
    getAdress:'api/customer/selCustomerAddress',
    //修改地址
    updateAdress:'api/customer/saveCustomerAddress',
    //删除地址
    delAdress:'api/customer/delAddress',
    //设为默认地址
    defaultAdress:'api/customer/updDefAddress/',
    addGiftcard:'api/giftcard/bondGiftcard',
    Creitcard:'api/pg/card/query/card',
    addCreitcard:'api/pg/card/bind/card',
    delCreitcard:'api/pg/card/del/card',
    //获取用户全部信息
    getAllUserInfo:'api/customer/queryCustomerAllInfo',
    //更新用户信息
    updateCustomer:"api/customer/updateCustomer",
    getCateGoods:'api/search/query',
    getGoodsDetails:'api/goods/getGoodsDetails',
    //获取店铺推荐商品
    getDetailStoreGoods:'api/goods/getStoreGoods',
    //获取店铺信息
    getStoreInfo:'api/store/getStoreById',
    //添加商品到购物车
    addCart:'/api/shopcart/add',

    Goodslike:'api/goods/follow',
    //获取购物车商品
    getCartGoods:'/api/shopcart/listv3',
    //删除单个购车商品
    delCartGoods:'api/shopcart/remove',
    //删除所有购物车商品
    delAllCartGoods:'api/shopcart/clearall',
    //把购物车的购物项添加到收藏夹
    favorite:'api/shopcart/favorite',
    //购物车商品数量增加
    addCartNumber:'api/shopcart/number',
    //加入订单
    subOrder:'/api/order/commitOrder',
    //立即购买
    buyNow:'api/order/immediateBuy',
    //购物车提交  
    cartSubmilt:'api/order/shoppingCart',
    //获取订单页优惠券
    getCouponActivity:"api/coupon/getCouponActivity",
    //计算优惠信息
    Compute:"api/order/view/discounts/compute",
    //获取全平台促销活动
    getMarketingBy:'api/market/getMarketingBy',
    //支付时获取信用卡列表
    getCard:"api/pg/card/query/card",
    //信用卡支付
    payCard:"api/pay/payCard",
    //确认支付
    affirmPayCard:"api/pay/affirmPayCard",
    //余额支付
    giftCardPay:"api/pay/giftCardPay",
    //购物车勾选
    CheckedCart:'api/shopcart/checked',
    //上传图片
    upImage:'api/image/upLoadImg',
    //关注商品
    likeGoods:'/api/goods/getFollows',
    //商品取消关注
    cancelLike:'api/goods/follow',
    returnGoods:'api/return/order/ways',
    returnGoodsList:'api/return/order/returnOrderInfoPage/10/1',
    returnDetail:'api/return/order/refundOrderDetails',
    //我的订单
    order:'api/order/queryOrderPage/10/1',
    //取消订单
    cancelOrder:"api/order/cancel",
    //确认收货
    confirmReceiving:'api/order/confirmReceiving',
    //是否可创建退单
    returnable:"api/return/order/returnable",
    //获取退货原因
    getReasons:"api/return/order/reasons",
    //获取退款方式
    getReturnType:"api/return/order/ways",
    //提交退款申请
    SubmitreturnOrder:"api/return/order/add",
    //获取退单详情
    refundOrderDetails:"api/return/order/refundOrderDetails",
    //取消退单
    cancelReturnOrder:'api/return/order/cancelReturnOrder',
    //获取订单详情
    getorderDetail:'api/order/orderDetail',
    //评论商品
    goodsEvaluate:"api/goods/goodsEvaluate",
    //店铺
    getStoreinfo:'api/store/getStoreById',
    //关住的店铺
    getFllowStore:"api/store/getStoreByCusId",
    //店铺的关注取关
    StoreFollow:'api/store/follow',
    //店铺是否关注
    isFollow:"api/store/getFollow",
    getStoreGoods:'api/store/getStoreGoods',
    getStoreCate:'api/store/getStoreCate',
    //获取店铺全部商品
    getGoods:'api/search/query',
    //交易明细
    getDeal:'api/pay/queryCardFlowInfoPage/10/1',
    //优惠券列表
    getCouponList:'api/coupon/getCusCouponById',
    //获取待领取优惠券
    getCouponActList:'api/coupon/getLoginCouponActList',
    //领取优惠券
    getCustomerCoupon:'api/coupon/getCustomerCoupon'


}